
name: $(buildversion)

pool:
  vmImage: 'windows-latest'

variables:
    - group: "Version Number"
    - group: "Marketplace"

trigger:
  paths:
    include:
    - azuredevops/powerbiactions

stages:
 - stage: build
   displayName: Build
   jobs:
    - job:
      pool: 'azure-scale-set-win'
      continueOnError: false
      steps:
       - template: steps/powerbiactions/build.yml
 - stage : Release
   displayName : Test
   condition: ne(variables['Build.Reason'], 'PullRequest')
   jobs:
    - deployment: DeployTest
      displayName: Deploy Extension to Test
      pool: 'azure-scale-set-win'
      environment: 'Extensions test'
      strategy:
        runOnce:
          deploy:
            steps:
            - template: steps/powerbiactions/test.yml